# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":timestamp"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d %H:%M:%S"

  - trigger: ":ra"
    replace: "→"

  - trigger: ":Ra"
    replace: "⇒"

  - trigger: ":rra"
    replace: "⇉"
    
  - trigger: ":la"
    replace: "←"

  - trigger: ":La"
    replace: "⇐"

  - trigger: ":lla"
    replace: "⇇"
    
  - trigger: ":ba"
    replace: "↔"

  - trigger: ":Ba"
    replace: "⇔"

  - trigger: ":lra"
    replace: "⇆"
    
  - trigger: ":rla"
    replace: "⇄"

  - trigger: ":ua"
    replace: "↑"

  - trigger: ":Ua"
    replace: "⇑"

  - trigger: ":uua"
    replace: "⇈"
    
  - trigger: ":da"
    replace: "↓"

  - trigger: ":Da"
    replace: "⇓"

  - trigger: ":dda"
    replace: "⇊"
    
  - trigger: ":aa"
    replace: "↕"

  - trigger: ":Aa"
    replace: "⇕"

  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"

  - trigger: ":ipython"
    replace: "from IPython import embed; embed()"

