# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

toggle_key: "RIGHT_ALT"

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:

  # Dates
  # Trigger with : so that they won't be triggered by ;da for example
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":timestamp"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d %H:%M:%S"

  - trigger: ";ra"
    replace: "→"

  - trigger: ";rua"
    replace: "⇒"

  - trigger: ";rra"
    replace: "⇉"
    
  - trigger: ";la"
    replace: "←"

  - trigger: ";lua"
    replace: "⇐"

  - trigger: ";lla"
    replace: "⇇"
    
  - trigger: ";ba"
    replace: "↔"

  - trigger: ";bua"
    replace: "⇔"

  - trigger: ";lra"
    replace: "⇆"
    
  - trigger: ";rla"
    replace: "⇄"

  - trigger: ";ua"
    replace: "↑"

  - trigger: ";uua"
    replace: "⇑"

  - trigger: ";uuua"
    replace: "⇈"
    
  - trigger: ";da"
    replace: "↓"

  - trigger: ";dua"
    replace: "⇓"

  - trigger: ";dda"
    replace: "⇊"
    
  - trigger: ";aa"
    replace: "↕"

  - trigger: ";aua"
    replace: "⇕"

  - trigger: ";lta"
    replace: "↖"

  - trigger: ";rta"
    replace: "↗"

  - trigger: ";rba"
    replace: "↘"

  - trigger: ";lba"
    replace: "↙"

  - trigger: ";shrug"
    replace: "¯\\_(ツ)_/¯"

  - trigger: ";ftable"
    replace: "(╯°□°）╯︵ ┻━┻"

  - trigger: ";ipython"
    replace: "from IPython import embed; embed()"

  - trigger: ";pd"
    replace: "import pandas as pd"

  - trigger: ";plt"
    replace: "import matplotlib.pyplot as plt"

  - trigger: ";np"
    replace: "import numpy as np"
